/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export function DesignModel(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/assets/abstract-sphere.gltf");

  useFrame(() => {
    if (group.current) {
      group.current.rotation.y += 0.01; // Adjust the speed of the rotation here
    }
  });

  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.part1.geometry}
        material={nodes.part1.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.part2.geometry}
        material={nodes.part2.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.part3.geometry}
        material={nodes.part3.material}
      />
    </group>
  );
}

useGLTF.preload("/assets/abstract-sphere.gltf");
